import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { AuthShell, RequestError } from '@/auth/layout'
import { consumeReturnTo, rememberReturnTo } from '@/auth/return-to'
import { sessionQueryKey } from '@/auth/session'
import { authApi } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import { Spinner } from '@/components/ui/spinner'

function Title({ title, children }: { title: string; children: ReactNode }) { return <><h1 className="text-2xl font-medium tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{children}</p></> }
function Password({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="grid gap-2"><Label htmlFor="password">Password</Label><Input autoComplete="current-password" id="password" minLength={12} onChange={(event) => onChange(event.target.value)} required type="password" value={value} /></div> }
function OAuthButtons() { const begin = (provider: 'github' | 'google') => { rememberReturnTo('/account'); window.location.assign(authApi.oauthUrl(provider)) }; return <div className="grid gap-3"><Button onClick={() => begin('github')} type="button" variant="outline">Continue with GitHub</Button><Button onClick={() => begin('google')} type="button" variant="outline">Continue with Google</Button></div> }
function token() { return new URLSearchParams(window.location.hash.slice(1)).get('token') }
function emailField(email: string, setEmail: (value: string) => void) { return <div className="grid gap-2"><Label htmlFor="email">Email</Label><Input autoComplete="email" id="email" onChange={(event) => setEmail(event.target.value)} required type="email" value={email} /></div> }

export function SignInPage() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const queryClient = useQueryClient(); const navigate = useNavigate(); const login = useMutation({ mutationFn: () => authApi.login(email, password), retry: false, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: sessionQueryKey }); navigate(consumeReturnTo(), { replace: true }) } }); return <AuthShell><Title title="Welcome back">Sign in to continue to Trace.</Title><form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); login.mutate() }}>{emailField(email, setEmail)}<Password onChange={setPassword} value={password} /><Button disabled={login.isPending} type="submit">{login.isPending ? <Spinner /> : null}Sign in</Button></form>{login.error ? <RequestError error={login.error} /> : null}<div className="my-6 flex items-center gap-3"><Separator /><span className="text-xs text-muted-foreground">or</span><Separator /></div><OAuthButtons /><p className="mt-6 text-sm text-muted-foreground">New to Trace? <Link className="text-link underline" to="/sign-up">Create an account</Link> · <Link className="text-link underline" to="/forgot-password">Forgot password?</Link></p></AuthShell> }
export function SignUpPage() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const register = useMutation({ mutationFn: () => authApi.register(email, password), retry: false }); return <AuthShell><Title title="Create your account">We will send a verification link before you can sign in.</Title><form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); register.mutate() }}>{emailField(email, setEmail)}<Password onChange={setPassword} value={password} /><Button disabled={register.isPending} type="submit">{register.isPending ? <Spinner /> : null}Create account</Button></form>{register.isSuccess ? <p className="mt-3 text-sm" role="status">{register.data.message}</p> : null}{register.error ? <RequestError error={register.error} /> : null}<p className="mt-6 text-sm text-muted-foreground">Already verified? <Link className="text-link underline" to="/sign-in">Sign in</Link></p></AuthShell> }
export function VerifyEmailPage() { const value = token(); const verify = useMutation({ mutationFn: () => authApi.verifyEmail(value ?? ''), retry: false }); return <AuthShell><Title title="Verify your email">Confirm your email address to enable password sign-in.</Title><Button className="mt-6 w-full" disabled={!value || verify.isPending} onClick={() => verify.mutate()}>{verify.isPending ? <Spinner /> : null}Verify email</Button>{verify.isSuccess ? <p className="mt-3 text-sm" role="status">Email verified. <Link className="text-link underline" to="/sign-in">Sign in</Link></p> : null}{verify.error ? <RequestError error={verify.error} /> : null}</AuthShell> }
export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const recover = useMutation({ mutationFn: () => authApi.recoverPassword(email), retry: false }); return <AuthShell><Title title="Reset your password">Enter your email and we will send instructions if an eligible account exists.</Title><form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); recover.mutate() }}>{emailField(email, setEmail)}<Button disabled={recover.isPending} type="submit">{recover.isPending ? <Spinner /> : null}Send instructions</Button></form>{recover.isSuccess ? <p className="mt-3 text-sm" role="status">{recover.data.message}</p> : null}{recover.error ? <RequestError error={recover.error} /> : null}</AuthShell> }
export function ResetPasswordPage() { const [password, setPassword] = useState(''); const value = token(); const reset = useMutation({ mutationFn: () => authApi.resetPassword(value ?? '', password), retry: false }); return <AuthShell><Title title="Choose a new password">Use at least 12 characters.</Title><form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); reset.mutate() }}><Password onChange={setPassword} value={password} /><Button disabled={!value || reset.isPending} type="submit">{reset.isPending ? <Spinner /> : null}Reset password</Button></form>{reset.isSuccess ? <p className="mt-3 text-sm" role="status">Password reset. <Link className="text-link underline" to="/sign-in">Sign in</Link></p> : null}{reset.error ? <RequestError error={reset.error} /> : null}</AuthShell> }
export function CallbackPage() { const [params] = useSearchParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const [error, setError] = useState<unknown>(); const sessionCheckStarted = useRef(false); const failed = params.get('error'); useEffect(() => { if (failed || sessionCheckStarted.current) return; sessionCheckStarted.current = true; void queryClient.fetchQuery({ queryKey: sessionQueryKey, queryFn: authApi.session, retry: false }).then(() => navigate(consumeReturnTo(), { replace: true })).catch(setError) }, [failed, navigate, queryClient]); return <AuthShell><Title title={failed ? 'Sign-in was not completed' : 'Finishing sign-in'}>{failed ? `Please try again. Request ID: ${params.get('request_id') ?? 'unavailable'}` : 'Checking your secure session.'}</Title>{failed ? <Link className="mt-6 inline-block text-link underline" to="/sign-in">Return to sign in</Link> : <div className="mt-6"><Spinner /></div>}{error ? <RequestError error={error} /> : null}</AuthShell> }
